language: rust
rust: stable
cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly

before_script: |
  set -e
  if [[ $TRAVIS_RUST_VERSION = 'stable' ]]; then
    rustup component add rustfmt clippy
  fi

script: |
  set -e
  cargo build
  cargo test
  if [[ $TRAVIS_RUST_VERSION = 'stable' ]]; then
    cargo fmt --all -- --check
    cargo clippy
  fi
  if [[ $TRAVIS_RUST_VERSION = 'nightly' ]]; then
    cargo bench
  fi

branches:
  only:
    # Pushes and PR to the master branch
    - master
    
notifications:
  email:
    on_success: never
